# Generated by Django 5.2.3 on 2025-07-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Farmer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="service",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=20)),
                ("harvest_date", models.DateField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Farmer.farmer"
                    ),
                ),
            ],
        ),
    ]
