# Generated by Django 5.2.3 on 2025-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Farmer", "0002_farmer_service_crop"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="area",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="planting_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="crop",
            name="price_per_m2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="harvest_date",
            field=models.DateField(null=True),
        ),
    ]
