# Generated by Django 5.2.3 on 2025-07-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Farmer", "0003_crop_area_crop_planting_date_crop_price_per_m2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
