# Generated by Django 5.2.3 on 2025-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
