# Generated by Django 5.2.3 on 2025-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date_joined_user_password_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
